<a href="https://colab.research.google.com/github/LogeshChandran/Huggingface_finetune/blob/main/testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Testing

In [ ]:
!pip install datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.3/474.3 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.9/39.9 MB 17.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 12.6 MB/s eta 0:00:00
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 14.0.2
    Uninstalling pyarrow-14.0.2:
      Successfully uninstalled pyarrow-14.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.4.1 requires pyarrow<15.0.0a0,>=14.0.1, but you have pyarrow 17.0.0 which is incompatible.
ibis-framework 8.0.0 requires pyarrow<16,>=2, but you have pyarrow 17.0.0 which is incompatible.


In [ ]:
from datasets import load_dataset

# ds = load_dataset("Logeshkc/newsroom")

In [ ]:

print(first_1000_dataset)


Dataset({
    features: ['url', 'archive', 'title', 'date', 'text', 'summary', 'compression', 'coverage', 'density', 'compression_bin', 'coverage_bin', 'density_bin', '__index_level_0__'],
    num_rows: 1000
})


In [1]:
! pip install transformers
! pip install datasets
! pip install sentencepiece
! pip install rouge_score
! pip install wandb
! pip install evaluate
! pip install torch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 kB 812.9 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.3/474.3 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.6/177.6 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 16.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 968.5 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.5/239.5 kB 12.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.6/124.6 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 446.8/446.8 kB 18.7 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.9.0
    Uninstalling fsspec-2024.9.0:
      Successfully uninstalled fsspec-2024.9.0
  Preparing metadata (setup.py) ... 

In [ ]:
import torch
import numpy as np
import datasets
import evaluate
from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    DataCollatorForSeq2Seq,
)

from tabulate import tabulate
import nltk
from datetime import datetime


#f1112bec2d2a9b22ac73033c91b302f44085a442


WANDB_INTEGRATION = True
# WANDB_INTEGRATION = False
if WANDB_INTEGRATION:
    import wandb
    wandb.login()



In [ ]:
model_name = "facebook/bart-large-cnn"
dataset_name = "Logeshkc/newsroom"

In [ ]:
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [7]:
encoder_max_length = 256  # demo
decoder_max_length = 64

In [8]:
from datasets import load_dataset,Dataset
from itertools import islice

def get_first_n_records(dataset_name, split_name, n_records):
    ds = load_dataset(dataset_name, split=split_name, streaming=True)
    first_n = list(islice(ds, n_records))
    first_n_dataset = Dataset.from_list(first_n)

    return first_n_dataset.to_pandas()

n_records = 2000

train_df = get_first_n_records(dataset_name, "train", n_records)
test_df = get_first_n_records(dataset_name, "test", n_records)
eval_df = get_first_n_records(dataset_name, "validation", n_records)

# print("Train Dataset:", train_df)
# print("Test Dataset:", test_df)
# print("Eval Dataset:", eval_df)


README.md:   0%|          | 0.00/988 [00:00<?, ?B/s]

In [9]:
train_df = train_df[train_df[:]['density_bin'] == 'abstractive']
test_df = test_df[test_df[:]['density_bin'] == 'abstractive']
eval_df = eval_df[eval_df[:]['density_bin'] == 'abstractive']

In [10]:
train_df = train_df[:10]
test_df = test_df[:10]
eval_df = eval_df[:10]

In [11]:
def remove_special_characters(df,column_name):
    df[column_name+'_clean'] = df[column_name].replace(r'\n', '.', regex=True).replace(r'\.\.+', '.', regex=True).replace(r'[^\w\s.]', '', regex=True).replace(r'[\t]', '', regex=True)
    return df

In [12]:
train_df = remove_special_characters(train_df,'text')
train_df = remove_special_characters(train_df,'summary')

test_df = remove_special_characters(test_df,'text')
test_df = remove_special_characters(test_df,'summary')

eval_df = remove_special_characters(eval_df,'text')
eval_df = remove_special_characters(eval_df,'summary')

In [13]:
train_df.head(1)

url  \
12  http://www.telegraph.co.uk/aboutus/careers-at-...   

                                              archive  \
12  http://web.archive.org/web/20091101154544id_/h...   

                                        title                       date  \
12  Careers at Telegraph Media Group: Culture 1970-08-21 12:51:41.154544   

                                                 text  \
12  Published: 2:56PM BST 09 Oct 2009\n\nMedia is ...   

                                              summary  compression  coverage  \
12  Telegraph Media Group operate a culture of kno...    10.928571  0.571429   

     density compression_bin coverage_bin  density_bin  __index_level_0__  \
12  0.714286             low          low  abstractive                 12   

                                           text_clean  \
12  Published 256PM BST 09 Oct 2009.Media is a ver...   

                                        summary_clean  
12  Telegraph Media Group operate a culture of kno...

In [14]:
test_df.head(1)

url  \
3  http://www.forbes.com/2010/05/12/iphone-blackb...   

                                             archive  \
3  http://web.archive.org/web/20120312144834id_/h...   

                                        title                       date  \
3  In Pictures: 10 Ways To Fix Your Cellphone 1970-08-21 20:58:32.144834   

                                                text  \
3  Like all gadgets, cellphones can break. In fac...   

                                             summary  compression  coverage  \
3  Simple home remedies for repairing your mobile...       4.3125       0.5   

   density compression_bin coverage_bin  density_bin  __index_level_0__  \
3    0.625             low          low  abstractive                  3   

                                          text_clean  \
3  Like all gadgets cellphones can break. In fact...   

                                       summary_clean  
3  Simple home remedies for repairing your mobile...

In [15]:
eval_df.head(1)

url  \
0  http://www.foxsports.com/baseball/xchange/team...   

                                             archive  \
0  http://web.archive.org/web/19980117162148id_/h...   

                      title                       date  \
0  Pro Sports Xchange notes 1970-08-20 06:01:57.162148   

                                                text  \
0  So sayeth Padre general manager Kevin Towers.\...   

                          summary  compression  coverage  density  \
0  SAN DIEGO PADRES team notebook        209.0       0.8      1.2   

  compression_bin coverage_bin  density_bin  __index_level_0__  \
0            high       medium  abstractive                  0   

                                          text_clean  \
0  So sayeth Padre general manager Kevin Towers.L...   

                    summary_clean  
0  SAN DIEGO PADRES team notebook

In [16]:
train_dataset = Dataset.from_pandas(train_df[['text_clean','summary_clean']])
test_dataset = Dataset.from_pandas(test_df[['text_clean','summary_clean']])
eval_dataset = Dataset.from_pandas(eval_df[['text_clean','summary_clean']])

In [17]:
def batch_tokenize_preprocess(batch, tokenizer, max_source_length, max_target_length):
  text, summary = batch["text_clean"], batch["summary_clean"]
  text_tokenized = tokenizer(text, max_length=max_source_length, truncation=True)
  summary_tokenized = tokenizer(summary, max_length=max_target_length, truncation=True)
  batch = {k: v for k, v in text_tokenized.items()}
  batch["labels"] = [
      -100 if token == tokenizer.pad_token_id else token
      for token in summary_tokenized["input_ids"]
  ]
  return batch

In [18]:
train_dataset

Dataset({
    features: ['text_clean', 'summary_clean', '__index_level_0__'],
    num_rows: 10
})

In [19]:
train_data = train_dataset.map(
    lambda batch: batch_tokenize_preprocess(
        batch, tokenizer, encoder_max_length, decoder_max_length
    ),
    batched=True,
    remove_columns=train_dataset.column_names,
)

test_data = test_dataset.map(
    lambda batch: batch_tokenize_preprocess(
        batch, tokenizer, encoder_max_length, decoder_max_length
    ),
    batched=True,
    remove_columns=test_dataset.column_names,
)

eval_data = eval_dataset.map(
    lambda batch: batch_tokenize_preprocess(
        batch, tokenizer, encoder_max_length, decoder_max_length
    ),
    batched=True,
    remove_columns=eval_dataset.column_names,
)


Map:   0%|          | 0/10 [00:00<?, ? examples/s]

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

In [20]:
# Borrowed from https://github.com/huggingface/transformers/blob/master/examples/seq2seq/run_summarization.py

nltk.download("punkt", quiet=True)

# metric = datasets.load_metric("rouge")
metric = evaluate.load("rouge")


def postprocess_text(preds, labels):
    print("preds",preds)
    print("labels",labels)
    preds = [pred.strip() for pred in preds]
    labels = [label.strip() for label in labels]

    # rougeLSum expects newline after each sentence
    preds = ["\n".join(nltk.sent_tokenize(pred)) for pred in preds]
    labels = ["\n".join(nltk.sent_tokenize(label)) for label in labels]
    print("\n\n")
    print("preds",preds)
    print("labels",labels)
    return preds, labels


def compute_metrics(eval_preds):
    print("eval_preds",eval_preds)
    preds, labels = eval_preds
    print("preds",preds)
    print("labels",labels)
    if isinstance(preds, tuple):
        preds = preds[0]
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
    print("decoded_preds",decoded_preds)
    # Replace -100 in the labels as we can't decode them.
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    print("labels",labels)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    print("decoded_labels",decoded_labels)

    # Some simple post-processing
    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)
    print("decoded_preds",decoded_preds)
    print("decoded_labels",decoded_labels)
    result = metric.compute(
        predictions=decoded_preds, references=decoded_labels, use_stemmer=True
    )
    print("result",result)
    # Extract a few results from ROUGE
    # result = {key: value.mid.fmeasure * 100 for key, value in result.items()}
    esult = {key: value * 100 for key, value in result.items()}
    print("result",esult)
    prediction_lens = [
        np.count_nonzero(pred != tokenizer.pad_token_id) for pred in preds
    ]
    print("prediction_lens",prediction_lens)
    result["gen_len"] = np.mean(prediction_lens)
    result = {k: round(v, 4) for k, v in result.items()}
    print("result",result)
    return result

In [21]:
training_args = Seq2SeqTrainingArguments(
    output_dir="results",
    num_train_epochs=1,  # demo
    do_train=True,
    do_eval=True,
    per_device_train_batch_size=4,  # demo
    per_device_eval_batch_size=4,
    learning_rate=3e-05,
    warmup_steps=500,
    weight_decay=0.1,
    label_smoothing_factor=0.1,
    predict_with_generate=True,
    logging_dir="logs",
    logging_steps=50,
    save_total_limit=3,
)

data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_data,
    eval_dataset=eval_data,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)

In [22]:
if WANDB_INTEGRATION:
    wandb_run = wandb.init(
        project="bart-large-cnn_newsroom",
        config={
            "per_device_train_batch_size": training_args.per_device_train_batch_size,
            "learning_rate": training_args.learning_rate,
            "dataset": "newsroom ",
            "model_name": model_name,
        },
    )

    now = datetime.now()
    current_time = now.strftime("%H%M%S")
    wandb_run.name = "run_" + current_time

wandb: Currently logged in as: logeshkc (logeshkc-student). Use `wandb login --relogin` to force relogin


In [23]:
eval_results_before = trainer.evaluate()

eval_preds <transformers.trainer_utils.EvalPrediction object at 0x7d5d255ff550>
preds [[    2     0 10006 ...     1     1     1]
 [    2     0   530 ...     1     1     1]
 [    2     0     0 ...     1     1     1]
 ...
 [    2     0   133 ...     1     1     1]
 [    2     0   495 ...     1     1     1]
 [    2     0 15243 ...     1     1     1]]
labels [[    0  9300 15795 ...     1     1     1]
 [    0 26615    66 ...     1     1     1]
 [    0 14181     5 ...     1     1     1]
 ...
 [    0   104 18995 ...     1     1     1]
 [    0 17105   661 ...     1     1     1]
 [    0  2264   436 ...     1     1     1]]
decoded_preds ['Mark Langston had elbow and knee problems last year and made only one start Aug. 20 after undergoing arthroscopic surgery in May to have bone spurs removed from his left elbow. Langston thinks it will. And Towers said its not that big a gamble.Right now were very happy with the rotation we have said Towers of the rotation.', 'Korean boy band Super Junior top th

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.


result {'rouge1': 0.11733538835085595, 'rouge2': 0.01978939724037763, 'rougeL': 0.07491946496240301, 'rougeLsum': 0.0898122273313667}
result {'rouge1': 11.733538835085595, 'rouge2': 1.978939724037763, 'rougeL': 7.491946496240301, 'rougeLsum': 8.98122273313667}
prediction_lens [73, 65, 102, 68, 77, 85, 86, 62, 83, 74]
result {'rouge1': 0.1173, 'rouge2': 0.0198, 'rougeL': 0.0749, 'rougeLsum': 0.0898, 'gen_len': 77.5}


In [24]:
%%wandb
# uncomment to display Wandb charts

trainer.train()

Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'max_length': 142, 'min_length': 56, 'early_stopping': True, 'num_beams': 4, 'length_penalty': 2.0, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}


TrainOutput(global_step=3, training_loss=5.17302926381429, metrics={'train_runtime': 337.5207, 'train_samples_per_second': 0.03, 'train_steps_per_second': 0.009, 'total_flos': 5417761505280.0, 'train_loss': 5.17302926381429, 'epoch': 1.0})

In [25]:
eval_results_after = trainer.evaluate()

eval_preds <transformers.trainer_utils.EvalPrediction object at 0x7d5d24dc8d60>
preds [[    2     0 10006 ...     1     1     1]
 [    2     0   530 ...     1     1     1]
 [    2     0     0 ...     1     1     1]
 ...
 [    2     0   133 ...     1     1     1]
 [    2     0   495 ...     1     1     1]
 [    2     0 15243 ...     1     1     1]]
labels [[    0  9300 15795 ...     1     1     1]
 [    0 26615    66 ...     1     1     1]
 [    0 14181     5 ...     1     1     1]
 ...
 [    0   104 18995 ...     1     1     1]
 [    0 17105   661 ...     1     1     1]
 [    0  2264   436 ...     1     1     1]]
decoded_preds ['Mark Langston had elbow and knee problems last year and made only one start Aug. 20 after undergoing arthroscopic surgery in May to have bone spurs removed from his left elbow. Langston thinks it will. And Towers said its not that big a gamble.Right now were very happy with the rotation we have said Towers of the rotation.', 'Korean boy band Super Junior top th

In [26]:
if WANDB_INTEGRATION:
    wandb_run.finish()

In [27]:
eval_results_after

{'eval_loss': 5.818817138671875,
 'eval_model_preparation_time': 0.0083,
 'eval_rouge1': 0.1173,
 'eval_rouge2': 0.0198,
 'eval_rougeL': 0.0749,
 'eval_rougeLsum': 0.0898,
 'eval_gen_len': 77.5,
 'eval_runtime': 149.0395,
 'eval_samples_per_second': 0.067,
 'eval_steps_per_second': 0.02,
 'epoch': 1.0}

In [28]:
import pandas as pd

# Convert the metric results into lists for element-wise operations
metrics = list(eval_results_before.keys())
before_values = list(eval_results_before.values())
after_values = list(eval_results_after.values())

# Compute the differences
differences = [after - before for before, after in zip(before_values, after_values)]

print(len(metrics),len(before_values),len(after_values),len(differences))
# Combine the results into a DataFrame for comparison
comparison_df = pd.DataFrame({
    'Metric': metrics,
    'Before Training': before_values,
    'After Training': after_values[:-1],
    'Difference': differences
})

print(comparison_df)


10 10 11 10
                        Metric  Before Training  After Training  Difference
0                    eval_loss         5.820386        5.818817   -0.001569
1  eval_model_preparation_time         0.008300        0.008300    0.000000
2                  eval_rouge1         0.117300        0.117300    0.000000
3                  eval_rouge2         0.019800        0.019800    0.000000
4                  eval_rougeL         0.074900        0.074900    0.000000
5               eval_rougeLsum         0.089800        0.089800    0.000000
6                 eval_gen_len        77.500000       77.500000    0.000000
7                 eval_runtime       155.693700      149.039500   -6.654200
8      eval_samples_per_second         0.064000        0.067000    0.003000
9        eval_steps_per_second         0.019000        0.020000    0.001000


In [29]:
eval_results_after.keys()

dict_keys(['eval_loss', 'eval_model_preparation_time', 'eval_rouge1', 'eval_rouge2', 'eval_rougeL', 'eval_rougeLsum', 'eval_gen_len', 'eval_runtime', 'eval_samples_per_second', 'eval_steps_per_second', 'epoch'])

In [30]:
eval_results_before.keys()

dict_keys(['eval_loss', 'eval_model_preparation_time', 'eval_rouge1', 'eval_rouge2', 'eval_rougeL', 'eval_rougeLsum', 'eval_gen_len', 'eval_runtime', 'eval_samples_per_second', 'eval_steps_per_second'])

In [31]:
# Predict on the test dataset
test_results = trainer.predict(test_data)

# The test results contain predictions and metrics (if compute_metrics is defined)
predictions, labels, metrics = test_results

# Print predictions and test metrics
print("Test Metrics:", metrics)
print("Predictions:", predictions)


eval_preds <transformers.trainer_utils.EvalPrediction object at 0x7d5d24137820>
preds [[    2     0  2522 ...     1     1     1]
 [    2     0   100 ...     1     1     1]
 [    2     0   970 ...     1     1     1]
 ...
 [    2     0   387 ...     1     1     1]
 [    2     0 14043 ...     1     1     1]
 [    2     0   846 ...     1     1     1]]
labels [[    0 45093   184 ...     1     1     1]
 [    0 32401 33280 ...     1     1     1]
 [    0   771 27698 ...     1     1     1]
 ...
 [    0   133  3390 ...     1     1     1]
 [    0 32139 12579 ...     1     1     1]
 [    0   846   833 ...     1     1     1]]
decoded_preds ['Our habit of carrying our phones constantly makes them more prone to breakage. Not all phone mishaps can be fixed but many can either at home or by professionals. For remedies to 10 common cellphone accidents read on. For more information on how to fix your phone click here.', 'I visited Saudi Arabia in September 2008 arriving in Riyadh the day Hurricane Ike sm

Error: You must call wandb.init() before wandb.log()

In [32]:
!pip install transformers huggingface_hub
!huggingface-cli login


    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    To login, `huggingface_hub` requires a token generated from https://huggingface.co/settings/tokens .
Enter your token (input will not be visible): 
Add token as git credential? (Y/n) n
Token is valid (permission: write).
Your token has been saved to /root/.cache/huggingface/token
Login successful


In [34]:
from huggingface_hub import create_repo

# Replace 'your-username' with your HF username and 'your-model-name' with the desired model repo name
repo_name = "Logeshkc/bart-large-cnn-newsroom"
create_repo(repo_name)

RepoUrl('https://huggingface.co/Logeshkc/bart-large-cnn-newsroom', endpoint='https://huggingface.co', repo_type='model', repo_id='Logeshkc/bart-large-cnn-newsroom')

In [35]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Assuming you have the trained model and tokenizer
# model = AutoModelForSeq2SeqLM.from_pretrained("path_to_your_model")
# tokenizer = AutoTokenizer.from_pretrained("path_to_your_tokenizer")

# Save your model and tokenizer locally before pushing
model.save_pretrained("bart-large-cnn-newsroom")
tokenizer.save_pretrained("bart-large-cnn-newsroom")

# Now push them to Hugging Face Hub
model.push_to_hub(repo_name)
tokenizer.push_to_hub(repo_name)

Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'max_length': 142, 'min_length': 56, 'early_stopping': True, 'num_beams': 4, 'length_penalty': 2.0, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'max_length': 142, 'min_length': 56, 'early_stopping': True, 'num_beams': 4, 'length_penalty': 2.0, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/Logeshkc/bart-large-cnn-newsroom/commit/e7cdfe23840a3de8b01207e62dcf040364e01987', commit_message='Upload tokenizer', commit_description='', oid='e7cdfe23840a3de8b01207e62dcf040364e01987', pr_url=None, pr_revision=None, pr_num=None)

In [37]:
trainer.save_model("bart-large-cnn-newsroom")
trainer.push_to_hub(repo_name)

Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'max_length': 142, 'min_length': 56, 'early_stopping': True, 'num_beams': 4, 'length_penalty': 2.0, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'max_length': 142, 'min_length': 56, 'early_stopping': True, 'num_beams': 4, 'length_penalty': 2.0, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_

CommitInfo(commit_url='https://huggingface.co/Logeshkc/results/commit/294c43722158690d9a571ba2ca5a54826cc07f1d', commit_message='Logeshkc/bart-large-cnn-newsroom', commit_description='', oid='294c43722158690d9a571ba2ca5a54826cc07f1d', pr_url=None, pr_revision=None, pr_num=None)

In [ ]:
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

# Load the model and tokenizer from the hub
model = AutoModelForSeq2SeqLM.from_pretrained(repo_name)
tokenizer = AutoTokenizer.from_pretrained(repo_name)